package com.mini.novel.crawlerservice.controller;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.mini.novel.common.result.Result;
import com.mini.novel.crawler.entity.*;
import com.mini.novel.crawler.mapper.*;
import com.mini.novel.crawlerservice.service.AuthorizedBookPolicy;
import com.mini.novel.crawler.service.CrawlerExecutionService;
import com.mini.novel.crawler.service.CompanyAuthorization;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.*;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/crawler/authorized-books")
public class AuthorizedBookController {
 private final CrawlerAuthorizedBookMapper books; private final CrawlerAuthorizedBookAuditMapper audits;
 private final CrawlerSourceConfigMapper sources; private final CrawlRankSourceMapper ranks; private final ObjectMapper json;
 private final CrawlTaskRecordMapper tasks; private final CrawlerExecutionService execution;
 public AuthorizedBookController(CrawlerAuthorizedBookMapper b,CrawlerAuthorizedBookAuditMapper a,CrawlerSourceConfigMapper s,CrawlRankSourceMapper r,ObjectMapper j,CrawlTaskRecordMapper t,CrawlerExecutionService e){books=b;audits=a;sources=s;ranks=r;json=j;tasks=t;execution=e;}
 @GetMapping public Result<Page<CrawlerAuthorizedBook>> list(@RequestParam(defaultValue="1") long page,@RequestParam(defaultValue="20") long size,@RequestParam(required=false) String keyword,@RequestParam(required=false) String sourceCode,@RequestParam(required=false) String authorizationStatus,@RequestParam(required=false) String reviewStatus,@RequestParam(required=false) String riskLevel){
  QueryWrapper<CrawlerAuthorizedBook> q=new QueryWrapper<>(); if(StringUtils.hasText(keyword))q.and(w->w.like("title",keyword).or().like("author",keyword).or().like("source_book_id",keyword)); eq(q,"source_code",sourceCode);eq(q,"authorization_status",authorizationStatus);eq(q,"review_status",reviewStatus);eq(q,"risk_level",riskLevel);q.orderByDesc("updated_at","id");return Result.ok(books.selectPage(new Page<>(Math.max(1,page),Math.min(100,Math.max(1,size))),q));}
 @GetMapping("/{id}") public Result<Map<String,Object>> detail(@PathVariable Long id){CrawlerAuthorizedBook b=books.selectById(id);if(b==null)return new Result<>(404,"Authorized book does not exist.",null);Map<String,Object> m=new LinkedHashMap<>();m.put("book",b);m.put("audits",audits.selectList(new QueryWrapper<CrawlerAuthorizedBookAudit>().eq("authorized_book_id",id).orderByDesc("created_at","id").last("LIMIT 200")));return Result.ok(m);}
 @GetMapping("/source-authorization/{sourceCode}") public Result<Map<String,Object>> sourceAuthorization(@PathVariable String sourceCode){CrawlerSourceConfig s=authorizedSource(sourceCode,false);Map<String,Object> out=new LinkedHashMap<>();out.put("sourceCode",s.sourceCode);out.put("sourceName",s.name);out.put("sourceType",s.sourceType);out.put("enabled",s.enabled);out.put("companyAuthorization",CompanyAuthorization.read(s));return Result.ok(out);}
 @PutMapping("/source-authorization/{sourceCode}") @Transactional public Result<Map<String,Object>> saveSourceAuthorization(@PathVariable String sourceCode,@RequestBody CompanyAuthorizationRequest r,@RequestHeader(value="X-Operator-Id",defaultValue="0")Long op){
  CrawlerSourceConfig s=authorizedSource(sourceCode,true);validateAgreement(r);LocalDateTime now=LocalDateTime.now();ObjectNode agreement=json.valueToTree(r);agreement.put("updatedBy",op);agreement.put("updatedAt",now.toString());
  try{ObjectNode root=(ObjectNode)json.readTree(StringUtils.hasText(s.ruleConfigJson)?s.ruleConfigJson:"{}");root.set("companyAuthorization",agreement);s.ruleConfigJson=json.writeValueAsString(root);}catch(Exception e){throw new IllegalArgumentException("Invalid source rule_config_json.");}s.updatedAt=now;sources.updateById(s);
  List<CrawlerAuthorizedBook> list=books.selectList(new QueryWrapper<CrawlerAuthorizedBook>().eq("source_code",sourceCode));int applied=0,skipped=0;for(CrawlerAuthorizedBook before:list){if("BLOCKED".equals(before.riskLevel)||"REJECTED".equals(before.authorizationStatus)||"REJECTED".equals(before.reviewStatus)){skipped++;continue;}CrawlerAuthorizedBook after=json.convertValue(before,CrawlerAuthorizedBook.class);CompanyAuthorization.apply(after,agreement);after.authorizedBy=op;after.reviewedBy=op;after.authorizedAt=now;after.reviewedAt=now;after.updatedAt=now;AuthorizedBookPolicy.validate(after);books.updateById(after);audit(before,after,op,"SOURCE_COMPANY_AUTHORIZATION","Agreement "+r.proofRef+" applied from adult source configuration.",now);applied++;}
  Map<String,Object> out=new LinkedHashMap<>();out.put("companyAuthorization",agreement);out.put("applied",applied);out.put("skipped",skipped);out.put("sourceEnabled",s.enabled);return Result.ok(out);}
 @PutMapping("/{id}") @Transactional public Result<CrawlerAuthorizedBook> update(@PathVariable Long id,@RequestBody Change c,@RequestHeader(value="X-Operator-Id",defaultValue="0")Long op){return apply(id,c,op);}
 @PostMapping("/batch") @Transactional public Result<List<CrawlerAuthorizedBook>> batch(@RequestBody BatchChange r,@RequestHeader(value="X-Operator-Id",defaultValue="0")Long op){if(r.ids==null||r.ids.isEmpty())return new Result<>(400,"Select at least one book.",null);List<CrawlerAuthorizedBook> out=new ArrayList<>();for(Long id:r.ids){Result<CrawlerAuthorizedBook>x=apply(id,r.change,op);if(x.code()!=0)throw new IllegalArgumentException(x.message());out.add(x.data());}return Result.ok(out);}
 @PostMapping("/collect-metadata") public Result<CrawlTaskRecord> collect(){CrawlerSourceConfig s=sources.selectOne(new QueryWrapper<CrawlerSourceConfig>().eq("source_code","xbookcn_authorized").last("LIMIT 1"));if(s==null||!Boolean.TRUE.equals(s.enabled))return new Result<>(409,"xbookcn source is disabled; metadata collection was not started.",null);if(s.ruleConfigJson==null||!s.ruleConfigJson.contains("metadataOnly")||!s.ruleConfigJson.contains("true"))return new Result<>(409,"xbookcn metadataOnly gate is not enabled; collection was not started.",null);CrawlRankSource rank=ranks.selectOne(new QueryWrapper<CrawlRankSource>().eq("source_id",s.id).eq("rank_type","SINGLE_BOOK_AUTHORIZED").eq("enabled",true).last("LIMIT 1"));if(rank==null)return new Result<>(409,"xbookcn rank is disabled; metadata collection was not started.",null);CrawlTaskRecord active=tasks.selectOne(new QueryWrapper<CrawlTaskRecord>().eq("source_id",s.id).eq("rank_source_id",rank.id).in("status",List.of("PENDING","RUNNING")).orderByDesc("id").last("LIMIT 1"));if(active!=null)return new Result<>(409,"An xbookcn metadata task is already pending or running.",active);LocalDateTime now=LocalDateTime.now();CrawlTaskRecord task=new CrawlTaskRecord();task.sourceId=s.id;task.rankSourceId=rank.id;task.taskType="METADATA_ONLY";task.triggerType="ADMIN_AUTHORIZED_BOOK_LIST";task.status="PENDING";task.targetUrl=rank.rankUrl+"#maxBooks="+Math.max(1,Math.min(100,rank.maxBooks==null?1:rank.maxBooks));task.totalCount=0;task.successCount=0;task.failCount=0;task.message="Authorized-book metadata task queued; chapter crawling and merge are disabled.";task.createdAt=now;task.updatedAt=now;tasks.insert(task);execution.executeAsync(task.id);return Result.ok(task);}
 private Result<CrawlerAuthorizedBook> apply(Long id,Change c,Long op){CrawlerAuthorizedBook before=books.selectById(id);if(before==null)return new Result<>(404,"Authorized book does not exist.",null);if(c==null)return new Result<>(400,"Change payload is required.",null);CrawlerAuthorizedBook after=json.convertValue(before,CrawlerAuthorizedBook.class);if(c.authorizationStatus!=null)after.authorizationStatus=c.authorizationStatus;if(c.reviewStatus!=null)after.reviewStatus=c.reviewStatus;if(c.riskLevel!=null)after.riskLevel=c.riskLevel;if(c.riskReason!=null)after.riskReason=c.riskReason;if(c.authorizationNote!=null)after.authorizationNote=c.authorizationNote;if(c.proofRef!=null)after.proofRef=c.proofRef;if(c.allowCrawlChapters!=null)after.allowCrawlChapters=c.allowCrawlChapters;if(c.allowStore!=null)after.allowStore=c.allowStore;if(c.allowDisplay!=null)after.allowDisplay=c.allowDisplay;if(c.allowVipDisplay!=null)after.allowVipDisplay=c.allowVipDisplay;AuthorizedBookPolicy.validate(after);LocalDateTime now=LocalDateTime.now();after.updatedAt=now;if(!Objects.equals(before.authorizationStatus,after.authorizationStatus)){after.authorizedBy=op;after.authorizedAt=now;}if(!Objects.equals(before.reviewStatus,after.reviewStatus)){after.reviewedBy=op;after.reviewedAt=now;}books.updateById(after);CrawlerAuthorizedBookAudit a=new CrawlerAuthorizedBookAudit();a.authorizedBookId=id;a.action=c.action==null?"UPDATE":c.action;a.operatorId=op;a.remark=c.remark;a.createdAt=now;try{a.beforeJson=json.writeValueAsString(before);a.afterJson=json.writeValueAsString(after);}catch(Exception e){throw new IllegalStateException(e);}audits.insert(a);return Result.ok(after);}
 private CrawlerSourceConfig authorizedSource(String code,boolean lock){CrawlerSourceConfig s=sources.selectOne(new QueryWrapper<CrawlerSourceConfig>().eq("source_code",code).last(lock?"FOR UPDATE":"LIMIT 1"));if(s==null)throw new IllegalArgumentException("Source does not exist.");if(!"AUTHORIZED_VIP".equals(s.sourceType))throw new IllegalArgumentException("Company authorization is only available for adult AUTHORIZED_VIP sources.");return s;}
 private void validateAgreement(CompanyAuthorizationRequest r){if(r==null||!StringUtils.hasText(r.authorizer)||!StringUtils.hasText(r.proofRef)||r.validFrom==null||r.validUntil==null)throw new IllegalArgumentException("Authorizer, contract/proof reference and validity dates are required.");if(r.validUntil.isBefore(r.validFrom))throw new IllegalArgumentException("validUntil must not precede validFrom.");if(Boolean.TRUE.equals(r.allowVipDisplay)&&!Boolean.TRUE.equals(r.allowDisplay))throw new IllegalArgumentException("VIP display requires display permission.");}
 private void audit(CrawlerAuthorizedBook before,CrawlerAuthorizedBook after,Long op,String action,String remark,LocalDateTime now){CrawlerAuthorizedBookAudit a=new CrawlerAuthorizedBookAudit();a.authorizedBookId=before.id;a.action=action;a.operatorId=op;a.remark=remark;a.createdAt=now;try{a.beforeJson=json.writeValueAsString(before);a.afterJson=json.writeValueAsString(after);}catch(Exception e){throw new IllegalStateException(e);}audits.insert(a);}
 private static void eq(QueryWrapper<?>q,String c,String v){if(StringUtils.hasText(v))q.eq(c,v);}
 public static class Change{public String authorizationStatus,reviewStatus,riskLevel,riskReason,authorizationNote,proofRef,action,remark;public Boolean allowCrawlChapters,allowStore,allowDisplay,allowVipDisplay;}
 public static class BatchChange{public List<Long> ids;public Change change;}
 public static class CompanyAuthorizationRequest{public String authorizer,proofRef,contractNo;public LocalDate validFrom,validUntil;public Boolean allowCrawlChapters,allowStore,allowDisplay,allowVipDisplay;public String remark;}
 @ExceptionHandler(IllegalArgumentException.class) @ResponseStatus(org.springframework.http.HttpStatus.BAD_REQUEST)
 public Result<Void> invalid(IllegalArgumentException e){return Result.fail(400,e.getMessage());}
}
