-- 工单模块（C 端用户给服务端提工单，后台查看/回复）
-- 幂等：CREATE TABLE IF NOT EXISTS

USE mini_novel;

CREATE TABLE IF NOT EXISTS ticket (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL COMMENT '提交人用户 id',
  title VARCHAR(100) NOT NULL COMMENT '标题',
  content VARCHAR(300) NOT NULL COMMENT '正文（标题+正文合计 ≤300 字）',
  status VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN=待处理 / CLOSED=已关闭',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_user (user_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单';

CREATE TABLE IF NOT EXISTS ticket_reply (
  id BIGINT NOT NULL AUTO_INCREMENT,
  ticket_id BIGINT NOT NULL COMMENT '工单 id',
  content VARCHAR(1000) NOT NULL COMMENT '回复内容',
  replier_type VARCHAR(16) NOT NULL COMMENT 'USER=用户 / ADMIN=管理员',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_ticket (ticket_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单回复';
