SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE mini_novel.category COMMENT='小说分类表，维护 H5 首页、分类页和后台分类管理使用的分类字典';
ALTER TABLE mini_novel.category
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '分类主键 ID',
  MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '分类名称，如玄幻、都市、仙侠',
  MODIFY COLUMN sort INT NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前';

ALTER TABLE mini_novel.novel COMMENT='业务小说主表，仅保存已通过清洗、可在 H5 展示或管理端维护的小说';
ALTER TABLE mini_novel.novel
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '小说主键 ID',
  MODIFY COLUMN title VARCHAR(128) NOT NULL COMMENT '小说标题',
  MODIFY COLUMN author VARCHAR(64) NOT NULL DEFAULT '' COMMENT '作者名称',
  MODIFY COLUMN cover_url VARCHAR(512) NULL COMMENT '封面图片地址',
  MODIFY COLUMN intro TEXT NULL COMMENT '小说简介',
  MODIFY COLUMN category_id BIGINT NULL COMMENT '分类 ID，关联 category.id',
  MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '小说状态枚举：0=下架，1=连载，2=完结',
  MODIFY COLUMN vip_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否 VIP 小说：0=否，1=是；H5 用于区分 VIP 展示',
  MODIFY COLUMN free_chapter_count INT NOT NULL DEFAULT 0 COMMENT '免费章节数量，超过后可按 VIP 权限控制',
  MODIFY COLUMN word_count BIGINT NOT NULL DEFAULT 0 COMMENT '总字数，来自采集或人工维护',
  MODIFY COLUMN latest_chapter_id BIGINT NULL COMMENT '最新章节 ID，关联 chapter.id',
  MODIFY COLUMN latest_chapter_title VARCHAR(255) NULL COMMENT '最新章节标题冗余字段',
  MODIFY COLUMN source_url VARCHAR(512) NULL COMMENT '来源页面地址或人工导入来源标识',
  MODIFY COLUMN offline_reason VARCHAR(255) NULL COMMENT '下架原因',
  MODIFY COLUMN offline_at DATETIME NULL COMMENT '下架时间',
  MODIFY COLUMN operator_id BIGINT NULL COMMENT '最近一次后台操作人 ID',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel.chapter COMMENT='业务章节表，保存 H5 阅读端可读取的章节元数据和正文';
ALTER TABLE mini_novel.chapter
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '章节主键 ID',
  MODIFY COLUMN novel_id BIGINT NOT NULL COMMENT '小说 ID，关联 novel.id',
  MODIFY COLUMN chapter_no INT NOT NULL COMMENT '章节序号，同一本小说内唯一',
  MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '章节标题',
  MODIFY COLUMN content LONGTEXT NULL COMMENT '章节正文；兼容旧结构，后续大正文优先使用 chapter_content',
  MODIFY COLUMN is_vip TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否 VIP 章节：0=免费，1=VIP',
  MODIFY COLUMN price_coin INT NOT NULL DEFAULT 0 COMMENT '章节价格，单位为站内虚拟币；0 表示免费或 VIP 包含',
  MODIFY COLUMN source_url VARCHAR(512) NULL COMMENT '章节来源地址',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel.chapter_content COMMENT='章节正文扩展表，用于承载 LONGTEXT 正文、正文哈希和外部存储路径';
ALTER TABLE mini_novel.chapter_content
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '正文记录主键 ID',
  MODIFY COLUMN chapter_id BIGINT NOT NULL COMMENT '章节 ID，关联 chapter.id，一章一条正文记录',
  MODIFY COLUMN content LONGTEXT NULL COMMENT '章节完整正文，MySQL LONGTEXT 最大约 4GB 字节',
  MODIFY COLUMN content_hash VARCHAR(64) NULL COMMENT '正文 SHA-256 或其他哈希，用于去重和变更检测',
  MODIFY COLUMN storage_type VARCHAR(16) NOT NULL DEFAULT 'MYSQL' COMMENT '正文存储方式枚举：MYSQL=存 MySQL，FILE=文件/对象存储',
  MODIFY COLUMN content_path VARCHAR(512) NULL COMMENT '当 storage_type=FILE 时的文件或对象存储路径',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel.chapter_segment COMMENT='章节分段表，预留给超长章节切片、分页阅读或全文索引使用';
ALTER TABLE mini_novel.chapter_segment
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '分段主键 ID',
  MODIFY COLUMN chapter_id BIGINT NOT NULL COMMENT '章节 ID，关联 chapter.id',
  MODIFY COLUMN segment_no INT NOT NULL COMMENT '分段序号，同一章节内唯一',
  MODIFY COLUMN content LONGTEXT NULL COMMENT '分段正文内容',
  MODIFY COLUMN word_count INT NOT NULL DEFAULT 0 COMMENT '分段字数',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE mini_novel.app_user COMMENT='前台用户表，保存 H5 登录用户基础资料和 VIP 状态';
ALTER TABLE mini_novel.app_user
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户主键 ID',
  MODIFY COLUMN nickname VARCHAR(64) NOT NULL DEFAULT '' COMMENT '用户昵称',
  MODIFY COLUMN avatar VARCHAR(512) NULL COMMENT '头像地址',
  MODIFY COLUMN mobile VARCHAR(32) NULL COMMENT '手机号，唯一',
  MODIFY COLUMN email VARCHAR(128) NULL COMMENT '邮箱，唯一',
  MODIFY COLUMN password_hash VARCHAR(255) NULL COMMENT '登录密码哈希',
  MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '用户状态枚举：0=禁用，1=正常',
  MODIFY COLUMN vip_status TINYINT NOT NULL DEFAULT 0 COMMENT 'VIP 状态枚举：0=非 VIP，1=VIP 生效，2=已过期/失效',
  MODIFY COLUMN vip_expire_time DATETIME NULL COMMENT 'VIP 到期时间',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel.user_bookshelf COMMENT='用户书架表，记录用户收藏小说和最近阅读进度';
ALTER TABLE mini_novel.user_bookshelf
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '书架记录主键 ID',
  MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户 ID，关联 app_user.id',
  MODIFY COLUMN novel_id BIGINT NOT NULL COMMENT '小说 ID，关联 novel.id',
  MODIFY COLUMN last_chapter_id BIGINT NULL COMMENT '最近阅读章节 ID',
  MODIFY COLUMN progress INT NOT NULL DEFAULT 0 COMMENT '阅读进度百分比或客户端进度值',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel.user_read_history COMMENT='用户阅读历史表，记录用户最近阅读章节和阅读时间';
ALTER TABLE mini_novel.user_read_history
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '阅读历史主键 ID',
  MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户 ID，关联 app_user.id',
  MODIFY COLUMN novel_id BIGINT NOT NULL COMMENT '小说 ID，关联 novel.id',
  MODIFY COLUMN chapter_id BIGINT NOT NULL COMMENT '章节 ID，关联 chapter.id',
  MODIFY COLUMN progress INT NOT NULL DEFAULT 0 COMMENT '章节内阅读进度',
  MODIFY COLUMN read_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '阅读时间';

ALTER TABLE mini_novel.vip_plan COMMENT='VIP 套餐表，后台维护可购买或可授予的 VIP 套餐';
ALTER TABLE mini_novel.vip_plan
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '套餐主键 ID',
  MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '套餐名称',
  MODIFY COLUMN duration_days INT NOT NULL COMMENT '套餐有效天数',
  MODIFY COLUMN price DECIMAL(10,2) NOT NULL COMMENT '销售价格',
  MODIFY COLUMN original_price DECIMAL(10,2) NULL COMMENT '原价/划线价',
  MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：0=停用，1=启用',
  MODIFY COLUMN sort INT NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前',
  MODIFY COLUMN description VARCHAR(255) NULL COMMENT '套餐说明',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel.user_vip COMMENT='用户 VIP 权益表，记录用户当前或历史 VIP 有效期';
ALTER TABLE mini_novel.user_vip
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户 VIP 主键 ID',
  MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户 ID，关联 app_user.id',
  MODIFY COLUMN vip_plan_id BIGINT NULL COMMENT 'VIP 套餐 ID，关联 vip_plan.id；后台手工调整可为空',
  MODIFY COLUMN start_time DATETIME NOT NULL COMMENT 'VIP 开始时间',
  MODIFY COLUMN end_time DATETIME NOT NULL COMMENT 'VIP 结束时间',
  MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '权益状态枚举：0=失效，1=生效',
  MODIFY COLUMN source_order_id BIGINT NULL COMMENT '来源订单 ID，关联 vip_order.id',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel.vip_order COMMENT='VIP 订单表，记录用户购买 VIP 的订单和支付状态';
ALTER TABLE mini_novel.vip_order
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '订单主键 ID',
  MODIFY COLUMN order_no VARCHAR(64) NOT NULL COMMENT '订单号，唯一',
  MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户 ID，关联 app_user.id',
  MODIFY COLUMN vip_plan_id BIGINT NOT NULL COMMENT '套餐 ID，关联 vip_plan.id',
  MODIFY COLUMN amount DECIMAL(10,2) NOT NULL COMMENT '订单金额',
  MODIFY COLUMN pay_status TINYINT NOT NULL DEFAULT 0 COMMENT '支付状态枚举：0=待支付，1=已支付，2=已取消，3=已退款',
  MODIFY COLUMN pay_channel VARCHAR(32) NULL COMMENT '支付渠道，如 wechat、alipay、manual',
  MODIFY COLUMN paid_at DATETIME NULL COMMENT '支付完成时间',
  MODIFY COLUMN expire_at DATETIME NULL COMMENT '订单过期时间',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel.vip_adjust_log COMMENT='VIP 后台调整日志表，记录管理员直接调整用户 VIP 状态的审计信息';
ALTER TABLE mini_novel.vip_adjust_log
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '调整日志主键 ID',
  MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '被调整用户 ID',
  MODIFY COLUMN action VARCHAR(32) NOT NULL COMMENT '调整动作枚举：GRANT=开通/延长，REVOKE=取消，EXPIRE=置为过期，CORRECT=纠正',
  MODIFY COLUMN before_expire_time DATETIME NULL COMMENT '调整前 VIP 到期时间',
  MODIFY COLUMN after_expire_time DATETIME NULL COMMENT '调整后 VIP 到期时间',
  MODIFY COLUMN before_status VARCHAR(32) NULL COMMENT '调整前状态',
  MODIFY COLUMN after_status VARCHAR(32) NULL COMMENT '调整后状态',
  MODIFY COLUMN days INT NULL COMMENT '调整天数，正数延长，负数扣减',
  MODIFY COLUMN reason VARCHAR(255) NULL COMMENT '调整原因',
  MODIFY COLUMN operator_id BIGINT NULL COMMENT '后台操作人 ID',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE mini_novel.crawl_source COMMENT='旧版采集源表，早期单体采集配置，后续以 mini_novel_crawler.crawl_source 为准';
ALTER TABLE mini_novel.crawl_source
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '旧版采集源主键 ID',
  MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '旧版采集源名称',
  MODIFY COLUMN base_url VARCHAR(512) NOT NULL COMMENT '旧版采集源基础地址',
  MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：0=停用，1=启用',
  MODIFY COLUMN rule_config_json JSON NULL COMMENT '旧版解析规则 JSON',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel.crawl_task COMMENT='旧版采集任务表，早期单体任务记录，后续以 mini_novel_crawler.crawl_task_v2 为准';
ALTER TABLE mini_novel.crawl_task
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '旧版任务主键 ID',
  MODIFY COLUMN source_id BIGINT NOT NULL COMMENT '旧版采集源 ID',
  MODIFY COLUMN novel_id BIGINT NULL COMMENT '关联业务小说 ID',
  MODIFY COLUMN task_type VARCHAR(32) NOT NULL COMMENT '任务类型，如 LIST、DETAIL、CHAPTER',
  MODIFY COLUMN status TINYINT NOT NULL DEFAULT 0 COMMENT '任务状态枚举：0=待执行，1=成功，2=失败',
  MODIFY COLUMN message VARCHAR(1024) NULL COMMENT '任务执行消息或失败原因',
  MODIFY COLUMN retry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  MODIFY COLUMN started_at DATETIME NULL COMMENT '开始时间',
  MODIFY COLUMN finished_at DATETIME NULL COMMENT '结束时间',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE mini_novel.novel_identity COMMENT='小说统一身份表，用于跨采集源识别同一本小说，避免重复入库';
ALTER TABLE mini_novel.novel_identity
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '身份主键 ID',
  MODIFY COLUMN canonical_title VARCHAR(128) NOT NULL COMMENT '标准书名',
  MODIFY COLUMN canonical_author VARCHAR(64) NOT NULL DEFAULT '' COMMENT '标准作者',
  MODIFY COLUMN normalized_title VARCHAR(128) NOT NULL COMMENT '归一化书名，用于去重匹配',
  MODIFY COLUMN normalized_author VARCHAR(64) NOT NULL DEFAULT '' COMMENT '归一化作者，用于去重匹配',
  MODIFY COLUMN novel_id BIGINT NULL COMMENT '已合并到的业务小说 ID，关联 novel.id',
  MODIFY COLUMN match_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '身份状态枚举：ACTIVE=有效，MERGED=已合并，IGNORED=忽略',
  MODIFY COLUMN confidence_score INT NOT NULL DEFAULT 100 COMMENT '匹配置信度，0-100',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel.novel_source_mapping COMMENT='小说来源映射表，记录各采集源书籍与统一身份/业务小说的关系';
ALTER TABLE mini_novel.novel_source_mapping
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '来源映射主键 ID',
  MODIFY COLUMN identity_id BIGINT NOT NULL COMMENT '小说统一身份 ID，关联 novel_identity.id',
  MODIFY COLUMN novel_id BIGINT NULL COMMENT '业务小说 ID，关联 novel.id；未入库时为空',
  MODIFY COLUMN source_code VARCHAR(64) NOT NULL COMMENT '采集源编码',
  MODIFY COLUMN source_book_id VARCHAR(128) NOT NULL COMMENT '来源站点书籍 ID',
  MODIFY COLUMN source_url VARCHAR(512) NULL COMMENT '来源站点书籍地址',
  MODIFY COLUMN source_title VARCHAR(128) NOT NULL COMMENT '来源站点书名',
  MODIFY COLUMN source_author VARCHAR(64) NOT NULL DEFAULT '' COMMENT '来源站点作者',
  MODIFY COLUMN content_status VARCHAR(32) NOT NULL DEFAULT 'META_ONLY' COMMENT '内容状态枚举：META_ONLY=仅元数据，CATALOG_READY=目录已抓，CONTENT_READY=正文可用，PENDING_REVIEW=待审核，FAILED=失败，IGNORED=忽略',
  MODIFY COLUMN match_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '匹配状态枚举：PENDING=待匹配，MATCHED=已匹配，MERGED=已入库，PARTIAL_MERGED=部分入库，PENDING_REVIEW=待审核，FAILED=失败，IGNORED=忽略',
  MODIFY COLUMN confidence_score INT NOT NULL DEFAULT 0 COMMENT '来源匹配置信度，0-100',
  MODIFY COLUMN last_crawled_at DATETIME NULL COMMENT '最近采集时间',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel.chapter_source_mapping COMMENT='章节来源映射表，记录来源章节与业务章节的对应关系和清洗状态';
ALTER TABLE mini_novel.chapter_source_mapping
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '章节映射主键 ID',
  MODIFY COLUMN novel_mapping_id BIGINT NOT NULL COMMENT '小说来源映射 ID，关联 novel_source_mapping.id',
  MODIFY COLUMN chapter_id BIGINT NULL COMMENT '业务章节 ID，关联 chapter.id；未入库时为空',
  MODIFY COLUMN source_chapter_id VARCHAR(128) NOT NULL COMMENT '来源站点章节 ID',
  MODIFY COLUMN source_url VARCHAR(512) NULL COMMENT '来源章节地址',
  MODIFY COLUMN source_title VARCHAR(255) NOT NULL COMMENT '来源章节标题',
  MODIFY COLUMN chapter_no INT NOT NULL COMMENT '来源章节序号',
  MODIFY COLUMN is_vip TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否来源 VIP 章节：0=免费，1=VIP',
  MODIFY COLUMN content_hash CHAR(64) NULL COMMENT '来源正文哈希',
  MODIFY COLUMN content_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '内容状态枚举：PENDING=待处理，MERGED=已入库，PENDING_REVIEW=待审核，FAILED=失败，IGNORED=忽略',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel_crawler.crawl_source COMMENT='采集源配置表，定义可抓取的网站或导入源';
ALTER TABLE mini_novel_crawler.crawl_source
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '采集源主键 ID',
  MODIFY COLUMN source_code VARCHAR(64) NOT NULL COMMENT '采集源编码，系统内唯一，如 qidian_public',
  MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '采集源名称',
  MODIFY COLUMN base_url VARCHAR(512) NOT NULL COMMENT '采集源基础域名或入口地址',
  MODIFY COLUMN source_type VARCHAR(32) NOT NULL DEFAULT 'PUBLIC' COMMENT '来源类型枚举：PUBLIC=公开网页，AUTHORIZED_VIP=授权 VIP，IMPORT=手动导入',
  MODIFY COLUMN auth_mode VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT '认证方式枚举：NONE=无需认证，PASSWORD=账号密码，COOKIE=Cookie',
  MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：0=停用，1=启用',
  MODIFY COLUMN priority INT NOT NULL DEFAULT 100 COMMENT '采集优先级，越小越优先',
  MODIFY COLUMN remark VARCHAR(255) NULL COMMENT '备注',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel_crawler.crawl_rank_source COMMENT='榜单源配置表，定义月榜、周榜、完结榜等高热度入口';
ALTER TABLE mini_novel_crawler.crawl_rank_source
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '榜单源主键 ID',
  MODIFY COLUMN source_id BIGINT NOT NULL COMMENT '采集源 ID，关联 crawl_source.id',
  MODIFY COLUMN rank_name VARCHAR(64) NOT NULL COMMENT '榜单名称',
  MODIFY COLUMN rank_type VARCHAR(32) NOT NULL COMMENT '榜单类型枚举：MONTH=月榜，WEEK=周榜，COMPLETED=完结榜，HOT=热度榜',
  MODIFY COLUMN rank_url VARCHAR(512) NOT NULL COMMENT '榜单页面地址',
  MODIFY COLUMN prefer_completed TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否优先完结作品：0=否，1=是',
  MODIFY COLUMN max_books INT NOT NULL DEFAULT 50 COMMENT '单次最多采集书籍数',
  MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：0=停用，1=启用',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel_crawler.crawl_schedule COMMENT='采集调度计划表，维护每日固定时间抓取和清洗配置';
ALTER TABLE mini_novel_crawler.crawl_schedule
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '调度计划主键 ID',
  MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '计划名称',
  MODIFY COLUMN source_id BIGINT NULL COMMENT '采集源 ID；为空表示按服务逻辑选择可用源',
  MODIFY COLUMN credential_id BIGINT NULL COMMENT '授权凭据 ID，关联 crawl_source_credential.id',
  MODIFY COLUMN schedule_times VARCHAR(64) NOT NULL DEFAULT '00:00,08:00,14:00' COMMENT '每日执行时间列表，逗号分隔，如 00:00,08:00,14:00',
  MODIFY COLUMN timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '调度时区',
  MODIFY COLUMN crawl_public TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否抓取公开章节：0=否，1=是',
  MODIFY COLUMN crawl_vip TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否抓取授权 VIP 章节：0=否，1=是',
  MODIFY COLUMN auto_merge TINYINT(1) NOT NULL DEFAULT 1 COMMENT '采集完成后是否自动清洗入库：0=否，1=是',
  MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：0=停用，1=启用',
  MODIFY COLUMN last_run_at DATETIME NULL COMMENT '最近执行时间',
  MODIFY COLUMN next_run_at DATETIME NULL COMMENT '下次计划执行时间',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel_crawler.crawl_source_credential COMMENT='采集源账号凭据表，保存授权抓取所需账号、Cookie 和请求头';
ALTER TABLE mini_novel_crawler.crawl_source_credential
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '凭据主键 ID',
  MODIFY COLUMN source_id BIGINT NOT NULL COMMENT '采集源 ID，关联 crawl_source.id',
  MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '凭据名称',
  MODIFY COLUMN auth_mode VARCHAR(32) NOT NULL DEFAULT 'PASSWORD' COMMENT '认证方式枚举：PASSWORD=账号密码，COOKIE=Cookie',
  MODIFY COLUMN username VARCHAR(128) NULL COMMENT '登录用户名',
  MODIFY COLUMN password_cipher VARCHAR(1000) NULL COMMENT '密码密文或加密占位，不在前端明文回显',
  MODIFY COLUMN cookie_text TEXT NULL COMMENT 'Cookie 文本，用于授权抓取',
  MODIFY COLUMN headers_json JSON NULL COMMENT '额外请求头 JSON，如 User-Agent',
  MODIFY COLUMN login_url VARCHAR(512) NULL COMMENT '登录页面地址',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'UNVERIFIED' COMMENT '凭据状态枚举：UNVERIFIED=未校验，VALID=有效，INVALID=无效，EXPIRED=过期',
  MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：0=停用，1=启用',
  MODIFY COLUMN last_check_status VARCHAR(32) NULL COMMENT '最近一次校验结果',
  MODIFY COLUMN last_check_at DATETIME NULL COMMENT '最近一次校验时间',
  MODIFY COLUMN remark VARCHAR(255) NULL COMMENT '备注',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel_crawler.crawl_task_v2 COMMENT='采集任务表，记录每次手动或调度触发的采集执行情况';
ALTER TABLE mini_novel_crawler.crawl_task_v2
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '采集任务主键 ID',
  MODIFY COLUMN schedule_id BIGINT NULL COMMENT '调度计划 ID，手动任务可为空',
  MODIFY COLUMN source_id BIGINT NULL COMMENT '采集源 ID',
  MODIFY COLUMN rank_source_id BIGINT NULL COMMENT '榜单源 ID',
  MODIFY COLUMN credential_id BIGINT NULL COMMENT '授权凭据 ID',
  MODIFY COLUMN task_type VARCHAR(32) NOT NULL COMMENT '任务类型枚举：PUBLIC=公开采集，VIP_AND_PUBLIC=公开+授权 VIP，IMPORT=手动导入',
  MODIFY COLUMN trigger_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '触发方式枚举：MANUAL=手动，SCHEDULE=调度，SYSTEM=系统补偿',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '任务状态枚举：PENDING=待执行，RUNNING=执行中，SUCCESS=成功，FAILED=失败',
  MODIFY COLUMN target_url VARCHAR(512) NULL COMMENT '本次采集目标 URL',
  MODIFY COLUMN total_count INT NOT NULL DEFAULT 0 COMMENT '发现或计划处理总数',
  MODIFY COLUMN success_count INT NOT NULL DEFAULT 0 COMMENT '成功处理数量',
  MODIFY COLUMN fail_count INT NOT NULL DEFAULT 0 COMMENT '失败数量',
  MODIFY COLUMN message VARCHAR(1000) NULL COMMENT '执行消息或失败原因',
  MODIFY COLUMN started_at DATETIME NULL COMMENT '开始时间',
  MODIFY COLUMN finished_at DATETIME NULL COMMENT '结束时间',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel_crawler.crawl_book_raw COMMENT='采集原始小说表，保存采集源返回的书籍元数据，尚未直接进入业务库';
ALTER TABLE mini_novel_crawler.crawl_book_raw
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '原始小说主键 ID',
  MODIFY COLUMN source_code VARCHAR(64) NOT NULL COMMENT '采集源编码',
  MODIFY COLUMN source_book_id VARCHAR(128) NOT NULL COMMENT '来源站点书籍 ID',
  MODIFY COLUMN source_url VARCHAR(512) NULL COMMENT '来源站点书籍地址',
  MODIFY COLUMN title VARCHAR(128) NOT NULL COMMENT '来源书名',
  MODIFY COLUMN author VARCHAR(64) NOT NULL DEFAULT '' COMMENT '来源作者',
  MODIFY COLUMN intro TEXT NULL COMMENT '来源简介',
  MODIFY COLUMN cover_url VARCHAR(512) NULL COMMENT '来源封面地址',
  MODIFY COLUMN category_name VARCHAR(64) NULL COMMENT '来源分类名称',
  MODIFY COLUMN book_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN' COMMENT '来源书籍状态枚举：UNKNOWN=未知，SERIALIZING=连载，COMPLETED=完结',
  MODIFY COLUMN word_count BIGINT NOT NULL DEFAULT 0 COMMENT '来源字数',
  MODIFY COLUMN heat_score BIGINT NOT NULL DEFAULT 0 COMMENT '热度分或榜单排序分',
  MODIFY COLUMN rank_type VARCHAR(32) NULL COMMENT '来源榜单类型：MONTH/WEEK/COMPLETED/HOT',
  MODIFY COLUMN content_status VARCHAR(32) NOT NULL DEFAULT 'META_ONLY' COMMENT '内容状态枚举：META_ONLY=仅元数据，CATALOG_READY=目录已抓，CONTENT_READY=正文已抓，PENDING_REVIEW=待审核，FAILED=失败',
  MODIFY COLUMN raw_json JSON NULL COMMENT '来源原始 JSON 或解析快照',
  MODIFY COLUMN crawled_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '采集时间',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel_crawler.crawl_chapter_raw COMMENT='采集原始章节表，保存来源章节目录和章节级元数据';
ALTER TABLE mini_novel_crawler.crawl_chapter_raw
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '原始章节主键 ID',
  MODIFY COLUMN book_raw_id BIGINT NOT NULL COMMENT '原始小说 ID，关联 crawl_book_raw.id',
  MODIFY COLUMN source_chapter_id VARCHAR(128) NOT NULL COMMENT '来源站点章节 ID',
  MODIFY COLUMN source_url VARCHAR(512) NULL COMMENT '来源章节地址',
  MODIFY COLUMN chapter_no INT NOT NULL COMMENT '章节序号',
  MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '来源章节标题',
  MODIFY COLUMN is_vip TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否来源 VIP 章节：0=免费，1=VIP',
  MODIFY COLUMN price_coin INT NOT NULL DEFAULT 0 COMMENT '来源章节价格或站内价格，0 表示免费',
  MODIFY COLUMN content_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '正文状态枚举：PENDING=待抓取，CONTENT_READY=正文已抓，PENDING_REVIEW=待审核，FAILED=失败',
  MODIFY COLUMN content_hash CHAR(64) NULL COMMENT '正文哈希',
  MODIFY COLUMN crawled_at DATETIME NULL COMMENT '章节采集时间',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel_crawler.crawl_content_raw COMMENT='采集原始正文表，保存原始章节正文，清洗通过后再写入业务库';
ALTER TABLE mini_novel_crawler.crawl_content_raw
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '原始正文主键 ID',
  MODIFY COLUMN chapter_raw_id BIGINT NOT NULL COMMENT '原始章节 ID，关联 crawl_chapter_raw.id',
  MODIFY COLUMN content LONGTEXT NOT NULL COMMENT '原始章节正文，必须是真实正文，不应仅为 URL 或 ID',
  MODIFY COLUMN content_hash CHAR(64) NOT NULL COMMENT '正文哈希，用于去重和变更检测',
  MODIFY COLUMN content_length INT NOT NULL DEFAULT 0 COMMENT '正文字符长度',
  MODIFY COLUMN storage_mode VARCHAR(32) NOT NULL DEFAULT 'MYSQL_LONGTEXT' COMMENT '存储模式枚举：MYSQL_LONGTEXT=MySQL 长文本，FILE=文件/对象存储',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE mini_novel_crawler.crawl_merge_task COMMENT='清洗入库任务表，记录从采集库清洗到业务库的一次执行结果';
ALTER TABLE mini_novel_crawler.crawl_merge_task
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '清洗任务主键 ID',
  MODIFY COLUMN crawl_task_id BIGINT NULL COMMENT '来源采集任务 ID，关联 crawl_task_v2.id',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '清洗状态枚举：PENDING=待清洗，MERGING=清洗中，MERGED=全部入库，PARTIAL_MERGED=部分入库，PENDING_REVIEW=待审核，FAILED=失败',
  MODIFY COLUMN total_count INT NOT NULL DEFAULT 0 COMMENT '处理书籍总数',
  MODIFY COLUMN merged_count INT NOT NULL DEFAULT 0 COMMENT '成功入库书籍数',
  MODIFY COLUMN pending_review_count INT NOT NULL DEFAULT 0 COMMENT '待审核书籍数',
  MODIFY COLUMN failed_count INT NOT NULL DEFAULT 0 COMMENT '失败书籍数',
  MODIFY COLUMN message VARCHAR(1000) NULL COMMENT '清洗结果说明或失败原因',
  MODIFY COLUMN started_at DATETIME NULL COMMENT '开始时间',
  MODIFY COLUMN finished_at DATETIME NULL COMMENT '结束时间',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE mini_novel_crawler.crawl_merge_item COMMENT='清洗明细表，记录每本原始小说的匹配、入库、待审核或忽略状态';
ALTER TABLE mini_novel_crawler.crawl_merge_item
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '清洗明细主键 ID',
  MODIFY COLUMN merge_task_id BIGINT NOT NULL COMMENT '清洗任务 ID，关联 crawl_merge_task.id',
  MODIFY COLUMN book_raw_id BIGINT NOT NULL COMMENT '原始小说 ID，关联 crawl_book_raw.id',
  MODIFY COLUMN identity_id BIGINT NULL COMMENT '小说统一身份 ID，关联 mini_novel.novel_identity.id',
  MODIFY COLUMN novel_id BIGINT NULL COMMENT '业务小说 ID，关联 mini_novel.novel.id；未入库时为空',
  MODIFY COLUMN match_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '明细状态枚举：PENDING=待处理，RETRYING=重新清洗中，MERGED=已入库，PARTIAL_MERGED=部分入库，PENDING_REVIEW=待审核，FAILED=失败，IGNORED=人工忽略',
  MODIFY COLUMN confidence_score INT NOT NULL DEFAULT 0 COMMENT '匹配置信度，0-100',
  MODIFY COLUMN message VARCHAR(1000) NULL COMMENT '明细处理说明、待审核原因或失败原因',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
