spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mini-novel-mysql:3306/mini_novel?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=Asia/Shanghai}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:mini-novel-redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      database: ${SPRING_DATA_REDIS_DATABASE:0}
