spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mini-novel-mysql:3306/mini_novel?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=Asia/Shanghai}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
